### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by agileago** [superwf/ts-gear#13]
这个库非常好用，但使用中感觉到一些不足，下面是我在使用中的一些建议

- 允许不生成 `.gitignore`文件
- index.ts 只导出请求接口，目前ts提示的东西太多，无法精确定位一个请求接口,或者request文件只导出请求
- 允许不生成`mock`代码
- 请求体是否可自定义，目前觉得生成的请求函数感觉可以更简洁一些
```typescript
export const postAddressList = /* #__PURE__ */ (() => {
  const method = 'post'
  const url = '/address/list'
  function postAddressList(
    option?: PostAddressListOption,
  ): Promise<PostAddressListResponseSuccess> {
    if (process.env.NODE_ENV === 'test') {
      return Promise.resolve(postAddressListMockData)
    }
    return requester(url, { method, ...option }) as Promise<PostAddressListResponseSuccess>
  }

  postAddressList.method = method
  postAddressList.url = url
  return postAddressList
})()
```
其中 `method`, `url`是常量值，没有必要用一个高阶函数再次导出请求函数
```typescript
export const postAddressList = /* #__PURE__ */ (option?: PostAddressListOption, config?: any) => {
  const method = 'post'
  const url = '/address/list'
  return requester<PostAddressListResponseSuccess>(url, { method, ...option }, config)
})
```

把返回结果的类型给到用户进行控制`IOC`, 增加一个`config`参数，允许用户针对某些方法做一些特殊的控制，比如在`axios`拦截函数里面可以做一些特殊处理

**Comment by agileago** [comment]
```typescript
requester(url, { method, ...option }) as Promise<PostAddressListResponseSuccess>

requester<PostAddressListResponseSuccess>(url, { method, ...option })
```
这段代码生成泛型是不是会更好, 有时候后端返回的是 `{ code: 0, data: [], msg: ''}`,想再通过请求拦截去掉这一层，但代码生成后就很难改了

**Comment by agileago** [comment]
接口的描述是有的，我的错误

**Comment by superwf** [comment]
感谢您的指正，您说的这些问题我有些确实思考过。目前这个项目的解析是按照我所在组的后端情况而做的比较多的定制，想要做成让更多人通用的模式确实还需要很多改进。
这些问题我将在之后的项目空闲时间段内分阶段的进行修正与改进～，应该还会有大版本号的更新。

**Comment by superwf** [comment]
由于一些逻辑需求，有些请求的http请求方法和url需要在代码中获取进行判断，不想硬编码这两个值所以就将这两个值挂在请求函数的属性上了。所以最初生成的请求函数是这样的
```
export const postAddressList = /* #__PURE__ */ (option?: PostAddressListOption, config?: any) => {
  return requester<PostAddressListResponseSuccess>('/address/list', { 'post', ...option }, config)
})
postAddressList.method = 'post'
postAddressList.url = '/address/list'
```

但由于在定义函数之后又进行了属性赋值，导致在最终编译生产代码时tree shake无法过滤掉那些从没被引入且使用过的请求函数，最终代码体积庞大。即使添加了  `/* #__PURE__ */` 注释也没用，具体为什么没有被tree shake掉我也没有研究明白。
所以之后改成了那种使用立即执行函数生成请求函数的样子，通过 `/* #__PURE__ */`，可以使没有使用的请求函数在打包时被干净的过滤掉，而且可以获取到http请求方法与url。

**Comment by agileago** [comment]
谢谢你的回复，觉得此项目是很有潜力成为一个**大星**项目的，觉得`pont`生成的代码太乱了，没你这个来的直观，简单，容易理解，项目中急切的要用就fork了一份，适配了一下，现在用起来还是很舒服的，希望以后做的更易用一点，💪💪💪
