### ISSUE TITLE
【新人求解】自动生成的接口里面的 `public`等修饰是根据后端swagger添加的吗

### ISSUE THREAD

**Issue by LbhFront-end** [superwf/ts-gear#2]
## 问题
从 `pont` issue 里面看到这个轮子，发现 `example`的示例里面生成的接口的 `class`会修饰符，这是跟 `pont`所不同的，想请问作者这是这个轮子自己生成的吗，还是这个需要后端swagger去做规范

```ts
export class Order {
  public id?: number
  public petId?: number
  public quantity?: number
  public shipDate?: string
  /**
   * Order Status
   */
  public status?: 'placed' | 'approved' | 'delivered'
  public complete?: boolean = false
}

```

**Comment by superwf** [comment]
我是这么设计的，所有后端接口暴露出来的属性，都应该是前端可以获取的，所以都使用public修饰，至于有些属性可能是以_开头，那是后端自身的命名不规范问题，再为了这种规则搞出一些隐晦的逻辑就有些添乱了，其实不加也行默认就是public，加上会更符合eslint的校验规则看着会符合我工程里的习惯。

其实有好几次都想用interface替代class的，因为只是限定类型而已，不需要最后ts编译成js的时候生成实际的js代码。但由于swagger的定义里有一些属性是可以有默认值的，所有最终选择了class这种方式可以把属性的默认值挂上去。

**Comment by LbhFront-end** [comment]
> 我是这么设计的，所有后端接口暴露出来的属性，都应该是前端可以获取的，所以都使用public修饰，至于有些属性可能是以_开头，那是后端自身的命名不规范问题，再为了这种规则搞出一些隐晦的逻辑就有些添乱了，其实不加也行默认就是public，加上会更符合eslint的校验规则看着会符合我工程里的习惯。
> 
> 其实有好几次都想用interface替代class的，因为只是限定类型而已，不需要最后ts编译成js的时候生成实际的js代码。但由于swagger的定义里有一些属性是可以有默认值的，所有最终选择了class这种方式可以把属性的默认值挂上去。

好的，了解了 谢谢大佬
