### ISSUE TITLE
OpenAPI3 支持得不是很好

### ISSUE THREAD

**Issue by sudongyuer** [superwf/ts-gear#23]
使用OpenAPI3 生成出来的 definition.ts
很多module为any类型
![image](https://user-images.githubusercontent.com/76603360/137617323-edd99639-d858-4705-890d-09917cd6c61f.png)

**Comment by superwf** [comment]
这个要看具体的 openapi 定义了，只要能生成具体类型的都尽量生成了，有很多情况是引用definitions错误，或者就没有对应的定义，最后解析不了才使用 any，让应用至少能跑起来~
如果确实有文档定义没问题，但是仍然生成 any，那是我的问题，欢迎提供具体例子，可以补全对应的处理。

**Comment by sudongyuer** [comment]
我们项目都是使用的stopLight生成的标准openapi3规范的yml或者json格式文件。swagger 官方的petstore这个api 我也试过了，也是definitions生成出来为any类型  https://petstore3.swagger.io/api/v3/openapi.json

**Comment by superwf** [comment]
用 https://petstore3.swagger.io/api/v3/openapi.json 这个解析了一下

生成结果
https://github.com/superwf/ts-gear-example/blob/39227ba9fb17bb7b418d99c2049b3f2d4252938d/src/service/petOpenapiV3/definition.ts
https://github.com/superwf/ts-gear-example/blob/39227ba9fb17bb7b418d99c2049b3f2d4252938d/src/service/petOpenapiV3/request.ts

我加了个解析 v3 的样例项目，您帮指正下哪个 any 解析有问题呀？

**Comment by sudongyuer** [comment]
之前的文件给删除了,现在在用另外一个库了，不知道是不是我自己使用有误造成的，看了您生成的文件是正确的

**Comment by superwf** [comment]
嗯嗯，openapi 转 ts 的库很多，各有一些自己适用的场景，针对自己的项目多试几个最好。
，我最近做了个对比，欢迎指正~
https://github.com/superwf/ts-gear-example
