### ISSUE TITLE
有配置项可以去除每次的请求参数中的 body 吗？

### ISSUE THREAD

**Issue by coderlfm** [superwf/ts-gear#24]
你好，我们这边接口都是 `post` 请求，通过这个工具生成的请求参数都会在外面套一层 body， 请问有配置方式可以去除这一层吗
`{ body: { name: 'js', age: '20' } }`  -> `{ name: 'js', age: '20' }`

**Comment by superwf** [comment]
谢谢您的反馈，关于这点我也参考过 openapi-generator 和 swagger-codegen 生成的代码，其他工具生成的代码有些是没有 query 、body 这层的，生成的请求函数直接接收数据那层的参数。
但我这边的情况有一些确实是 post 接口，而且也有 query 参数或 path 参数，就造成了一个请求里既有 query 或 path，也有body，都放在一个大参数中难以区分和处理。
关于这点我也有一些认同和考虑，可能会在之后的版本中通过配置实现。

**Comment by coderlfm** [comment]
好的，谢谢，期待后面的更新

**Comment by superwf** [comment]
4.7.1 中添加了 simplifyRequestOption 选项，设置为true 可实现该功能了
如果入参只有一个位置，比如 { query: { ... } } 这种的话，query 这层在传的时候就去掉了
如果入参有多个位置，则还是得手动指定传，比如 { path: { id:number}, body: {... } }

**Comment by coderlfm** [comment]
你好，我刚刚试了一下，发现依旧不行，我检查了一下 接口参数的入参除了 body 就只有 header，这种是没办法去掉body吗

**Comment by superwf** [comment]
你好，测试用的 openapi 文档有例子么，我调试下看看
